services:
  - type: web
    name: impraveen
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FEEDBACK_TO
        value: praveennigam1999@gmail.com
